import subprocess
from pprint import pprint
import os
data = [{"identifier": "siena_marble_herringbone_tiles", "outputs": [
    {"identifier": "diffuse", "label": "Diffuse", "type": "image", "uid": 2436038380,
     "usages": ["diffuse"],
     "value": "C:/Users/xVan/.sublender/c1f5e862-65f3-4b74-b0e2-1271c020258e/sublender_pkg_siena_marble_herringbone_tiles/Siena_Marble_Herringbone_Tiles/siena_marble_herringbone_tiles_siena_marble_herringbone_tiles_diffuse.png"}, {"identifier": "basecolor", "label": "Base Color", "type": "image", "uid": 2676292210, "usages": ["baseColor"], "value": "C:/Users/xVan/.sublender/c1f5e862-65f3-4b74-b0e2-1271c020258e/sublender_pkg_siena_marble_herringbone_tiles/Siena_Marble_Herringbone_Tiles/siena_marble_herringbone_tiles_siena_marble_herringbone_tiles_basecolor.png"},
    {
        "identifier": "normal", "label": "Normal", "type": "image", "uid": 2676292208, "usages": ["normal"], "value": "C:/Users/xVan/.sublender/c1f5e862-65f3-4b74-b0e2-1271c020258e/sublender_pkg_siena_marble_herringbone_tiles/Siena_Marble_Herringbone_Tiles/siena_marble_herringbone_tiles_siena_marble_herringbone_tiles_normal.png"}, {"identifier": "specular", "label": "Specular", "type": "image", "uid": 2436038376, "usages": ["specular"], "value": "C:/Users/xVan/.sublender/c1f5e862-65f3-4b74-b0e2-1271c020258e/sublender_pkg_siena_marble_herringbone_tiles/Siena_Marble_Herringbone_Tiles/siena_marble_herringbone_tiles_siena_marble_herringbone_tiles_specular.png"},
    {"identifier": "glossiness", "label": "Glossiness", "type": "image", "uid": 2436038373, "usages": ["glossiness"], "value": "C:/Users/xVan/.sublender/c1f5e862-65f3-4b74-b0e2-1271c020258e/sublender_pkg_siena_marble_herringbone_tiles/Siena_Marble_Herringbone_Tiles/siena_marble_herringbone_tiles_siena_marble_herringbone_tiles_glossiness.png"}, {"identifier": "roughness", "label": "Roughness", "type": "image", "uid": 2676292106, "usages": ["roughness"], "value": "C:/Users/xVan/.sublender/c1f5e862-65f3-4b74-b0e2-1271c020258e/sublender_pkg_siena_marble_herringbone_tiles/Siena_Marble_Herringbone_Tiles/siena_marble_herringbone_tiles_siena_marble_herringbone_tiles_roughness.png"}, {"identifier": "metallic", "label": "Metallic", "type": "image", "uid": 2676292104, "usages": ["metallic"], "value": "C:/Users/xVan/.sublender/c1f5e862-65f3-4b74-b0e2-1271c020258e/sublender_pkg_siena_marble_herringbone_tiles/Siena_Marble_Herringbone_Tiles/siena_marble_herringbone_tiles_siena_marble_herringbone_tiles_metallic.png"}, {"identifier": "height", "label": "Height", "type": "image", "uid": 2676292100, "usages": ["height"], "value": "C:/Users/xVan/.sublender/c1f5e862-65f3-4b74-b0e2-1271c020258e/sublender_pkg_siena_marble_herringbone_tiles/Siena_Marble_Herringbone_Tiles/siena_marble_herringbone_tiles_siena_marble_herringbone_tiles_height.png"}]}]
print(data[0]['outputs'][0]['value'])
